import { ColorValue } from 'react-native';

import { colorArray } from '../../utils/color';

const pinLockAnimation = (color: ColorValue) => {
  const cArray = colorArray(color);
  return {
    assets: [],
    ddd: 0,
    fr: 29.9700012207031,
    h: 130,
    ip: 0,
    layers: [
      {
        ao: 0,
        bm: 0,
        ddd: 0,
        ef: [
          {
            ef: [
              {
                ix: 1,
                mn: 'ADBE Radial Wipe-0001',
                nm: 'Transition Completion',
                ty: 0,
                v: { a: 0, ix: 1, k: 0 },
              },
              {
                ix: 2,
                mn: 'ADBE Radial Wipe-0002',
                nm: 'Start Angle',
                ty: 0,
                v: { a: 0, ix: 2, k: 0 },
              },
              {
                ix: 3,
                mn: 'ADBE Radial Wipe-0003',
                nm: 'Wipe Center',
                ty: 3,
                v: { a: 0, ix: 3, k: [65, 65] },
              },
              {
                ix: 4,
                mn: 'ADBE Radial Wipe-0004',
                nm: 'Wipe',
                ty: 7,
                v: { a: 0, ix: 4, k: 1 },
              },
              {
                ix: 5,
                mn: 'ADBE Radial Wipe-0005',
                nm: 'Feather',
                ty: 0,
                v: { a: 0, ix: 5, k: 0 },
              },
            ],
            en: 1,
            ix: 1,
            mn: 'ADBE Radial Wipe',
            nm: 'Radial Wipe',
            np: 7,
            ty: 26,
          },
        ],
        ind: 1,
        ip: 0,
        ks: {
          a: { a: 0, ix: 1, k: [0, 0, 0] },
          o: { a: 0, ix: 11, k: 100 },
          p: { a: 0, ix: 2, k: [64.75, 65, 0] },
          r: { a: 0, ix: 10, k: 0 },
          s: { a: 0, ix: 6, k: [100, 100, 100] },
        },
        nm: 'body',
        op: 1832.00007461889,
        shapes: [
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                d: 1,
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                p: { a: 0, ix: 3, k: [0, 0] },
                s: { a: 0, ix: 2, k: [86.041, 86.041] },
                ty: 'el',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: [0, 0, 0, 1] },
                hd: false,
                lc: 1,
                lj: 1,
                ml: 4,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 6 },
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [0.25, 0] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [100, 100] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 1,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 1',
            np: 2,
            ty: 'gr',
          },
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                d: 1,
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                p: { a: 0, ix: 3, k: [0, 0] },
                s: { a: 0, ix: 2, k: [9.352, 9.352] },
                ty: 'el',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: [0, 0, 0, 1] },
                hd: false,
                lc: 1,
                lj: 1,
                ml: 4,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 0 },
              },
              {
                bm: 0,
                c: { a: 0, ix: 4, k: [0, 0, 0, 1] },
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                o: { a: 0, ix: 5, k: 100 },
                r: 1,
                ty: 'fl',
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [0, -1.5] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [100, 100] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 2,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 2',
            np: 3,
            ty: 'gr',
          },
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                d: 1,
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                p: { a: 0, ix: 3, k: [0, 0] },
                s: { a: 0, ix: 2, k: [8.805, 8.805] },
                ty: 'el',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: [0, 0, 0, 1] },
                hd: false,
                lc: 1,
                lj: 1,
                ml: 4,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 0 },
              },
              {
                bm: 0,
                c: { a: 0, ix: 4, k: [0, 0, 0, 1] },
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                o: { a: 0, ix: 5, k: 100 },
                r: 1,
                ty: 'fl',
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [31.518, -36.291] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [100, 100] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 3,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 3',
            np: 3,
            ty: 'gr',
          },
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                d: 1,
                hd: false,
                mn: 'ADBE Vector Shape - Rect',
                nm: 'Rectangle Path 1',
                p: { a: 0, ix: 3, k: [0, 0] },
                r: { a: 0, ix: 4, k: 0 },
                s: { a: 0, ix: 2, k: [9.703, 8.758] },
                ty: 'rc',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: [0, 0, 0, 1] },
                hd: false,
                lc: 2,
                lj: 2,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 5 },
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [-0.145, -48.791] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [100, 100] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 4,
            mn: 'ADBE Vector Group',
            nm: 'Rectangle 1',
            np: 3,
            ty: 'gr',
          },
        ],
        sr: 1,
        st: 0,
        ty: 4,
      },
      {
        ao: 0,
        bm: 0,
        ddd: 0,
        ind: 2,
        ip: 0,
        ks: {
          a: { a: 0, ix: 1, k: [0, 0, 0] },
          o: { a: 0, ix: 11, k: 100 },
          p: { a: 0, ix: 2, k: [65, 65, 0] },
          r: {
            a: 1,
            ix: 10,
            k: [
              {
                i: { x: [0.833], y: [0.833] },
                o: { x: [0.167], y: [0.167] },
                s: [0],
                t: 0,
              },
              { s: [360], t: 1797.00007319331 },
            ],
          },
          s: { a: 0, ix: 6, k: [100, 100, 100] },
        },
        nm: 'arrow',
        op: 1798.00007323404,
        shapes: [
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                hd: false,
                ind: 0,
                ix: 1,
                ks: {
                  a: 0,
                  ix: 2,
                  k: {
                    c: false,
                    i: [
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [-0.25, 2.745],
                      [-0.25, -27.755],
                    ],
                  },
                },
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ty: 'sh',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: [0, 0, 0, 1] },
                hd: false,
                lc: 2,
                lj: 1,
                ml: 4,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 6 },
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [0, 5] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [-62.71, 157.64] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 1,
            mn: 'ADBE Vector Group',
            nm: 'Shape 1',
            np: 3,
            ty: 'gr',
          },
        ],
        sr: 1,
        st: 0,
        ty: 4,
      },
      {
        ao: 0,
        bm: 0,
        ddd: 0,
        ind: 3,
        ip: 0,
        ks: {
          a: { a: 0, ix: 1, k: [0, 0, 0] },
          o: { a: 0, ix: 11, k: 100 },
          p: { a: 0, ix: 2, k: [65.75, 65, 0] },
          r: { a: 0, ix: 10, k: 0 },
          s: { a: 0, ix: 6, k: [109.34, 109.34, 100] },
        },
        nm: 'yellow',
        op: 1798.00007323404,
        shapes: [
          {
            bm: 0,
            cix: 2,
            hd: false,
            it: [
              {
                hd: false,
                ind: 0,
                ix: 1,
                ks: {
                  a: 0,
                  ix: 2,
                  k: {
                    c: true,
                    i: [
                      [-2.232, 0],
                      [0, -2.232],
                      [2.232, 0],
                      [0, 2.232],
                    ],
                    o: [
                      [2.232, 0],
                      [0, 2.232],
                      [-2.232, 0],
                      [0, -2.232],
                    ],
                    v: [
                      [0, -4.042],
                      [4.042, 0],
                      [0, 4.042],
                      [-4.042, 0],
                    ],
                  },
                },
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ty: 'sh',
              },
              {
                bm: 0,
                c: { a: 0, ix: 3, k: cArray },
                hd: false,
                lc: 1,
                lj: 1,
                ml: 4,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                o: { a: 0, ix: 4, k: 100 },
                ty: 'st',
                w: { a: 0, ix: 5, k: 7 },
              },
              {
                a: { a: 0, ix: 1, k: [0, 0] },
                nm: 'Transform',
                o: { a: 0, ix: 7, k: 100 },
                p: { a: 0, ix: 2, k: [-0.874, -0.013] },
                r: { a: 0, ix: 6, k: 0 },
                s: { a: 0, ix: 3, k: [533.496, 533.496] },
                sa: { a: 0, ix: 5, k: 0 },
                sk: { a: 0, ix: 4, k: 0 },
                ty: 'tr',
              },
            ],
            ix: 1,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 2',
            np: 3,
            ty: 'gr',
          },
          {
            e: {
              a: 1,
              ix: 2,
              k: [
                {
                  i: { x: [0.833], y: [0.833] },
                  o: { x: [0.167], y: [0.167] },
                  s: [0],
                  t: 0,
                },
                { s: [100], t: 1797.00007319331 },
              ],
            },
            hd: false,
            ix: 2,
            m: 1,
            mn: 'ADBE Vector Filter - Trim',
            nm: 'Trim Paths 1',
            o: { a: 0, ix: 3, k: 0 },
            s: { a: 0, ix: 1, k: 0 },
            ty: 'tm',
          },
        ],
        sr: 1,
        st: 0,
        ty: 4,
      },
    ],
    markers: [{ cm: '1', dr: 0, tm: 86.0000035028518 }],
    nm: 'Comp 1',
    op: 1798.00007323404,
    v: '5.5.1',
    w: 130,
  };
};

export default pinLockAnimation;
