import type { ColorValue } from 'react-native';

import { colorArray } from '../utils/color';

const loading = (primaryColor: ColorValue, overlayColor: ColorValue) => {
  const primary = colorArray(primaryColor);
  const overlay = colorArray(overlayColor);

  return {
    v: '5.1.16',
    fr: 29.9700012207031,
    ip: 0,
    op: 17.0000006924242,
    w: 54,
    h: 54,
    nm: `loading-${String(primaryColor)}-${String(overlayColor)}`,
    ddd: 0,
    assets: [
      {
        id: 'comp_0',
        layers: [
          {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'シェイプレイヤー 4',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [0.833] },
                    o: { x: [0.167], y: [0.167] },
                    n: ['0p833_0p833_0p167_0p167'],
                    t: 1,
                    s: [-68],
                    e: [292],
                  },
                  { t: 17.0000006924242 },
                ],
                ix: 10,
              },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: overlay, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: { a: 0, k: 0, ix: 1 },
                e: { a: 0, k: 20, ix: 2 },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'シェイプレイヤー 3',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: -68, ix: 10 },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: primary, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: { a: 0, k: 0, ix: 1 },
                e: { a: 0, k: 100, ix: 2 },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
        ],
      },
    ],
    layers: [
      {
        ddd: 0,
        ind: 1,
        ty: 0,
        nm: 'pre3',
        refId: 'comp_0',
        sr: 1,
        ks: {
          o: { a: 0, k: 100, ix: 11 },
          r: { a: 0, k: 0, ix: 10 },
          p: { a: 0, k: [27, 27, 0], ix: 2 },
          a: { a: 0, k: [54, 54, 0], ix: 1 },
          s: { a: 0, k: [50, 50, 100], ix: 6 },
        },
        ao: 0,
        w: 108,
        h: 108,
        ip: 0,
        op: 90.0000036657751,
        st: 0,
        bm: 0,
      },
    ],
  };
};

const success = (primaryColor: ColorValue, overlayColor: ColorValue) => {
  const primary = colorArray(primaryColor);
  const overlay = colorArray(overlayColor);

  return {
    v: '5.1.16',
    fr: 29.9700012207031,
    ip: 0,
    op: 25.0000010182709,
    w: 54,
    h: 54,
    nm: `done-${String(primaryColor)}-${String(overlayColor)}`,
    ddd: 0,
    assets: [
      {
        id: 'comp_0',
        layers: [
          {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'check_longアウトライン',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [54, 54, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ind: 0,
                ty: 'sh',
                ix: 1,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [7.474, 35.526],
                      [43.075, 71],
                      [76, 39],
                    ],
                    c: false,
                  },
                  ix: 2,
                },
                nm: 'パス 1',
                mn: 'ADBE Vector Shape - Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 21,
                      s: [0],
                      e: [30],
                    },
                    { t: 25.0000010182709 },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [0],
                      e: [100],
                    },
                    { t: 24.00000097754 },
                  ],
                  ix: 2,
                },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
              {
                ty: 'st',
                c: { a: 0, k: overlay, ix: 3 },
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 6, ix: 5 },
                lc: 2,
                lj: 2,
                nm: '線 1',
                mn: 'ADBE Vector Graphic - Stroke',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'シェイプレイヤー 4',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [0.833] },
                    o: { x: [0.167], y: [0.167] },
                    n: ['0p833_0p833_0p167_0p167'],
                    t: 0,
                    s: [-68],
                    e: [220],
                  },
                  { t: 16.0000006516934 },
                ],
                ix: 10,
              },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: overlay, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [0],
                      e: [20],
                    },
                    { t: 21.0000008553475 },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 0,
                      s: [20],
                      e: [20],
                    },
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [20],
                      e: [20],
                    },
                    { t: 21.0000008553475 },
                  ],
                  ix: 2,
                },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 3,
            ty: 4,
            nm: 'シェイプレイヤー 3',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: -68, ix: 10 },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: primary, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: { a: 0, k: 0, ix: 1 },
                e: { a: 0, k: 100, ix: 2 },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
        ],
      },
    ],
    layers: [
      {
        ddd: 0,
        ind: 1,
        ty: 0,
        nm: 'pre4',
        refId: 'comp_0',
        sr: 1,
        ks: {
          o: { a: 0, k: 100, ix: 11 },
          r: { a: 0, k: 0, ix: 10 },
          p: { a: 0, k: [27, 27, 0], ix: 2 },
          a: { a: 0, k: [54, 54, 0], ix: 1 },
          s: { a: 0, k: [49.537, 49.537, 100], ix: 6 },
        },
        ao: 0,
        w: 108,
        h: 108,
        ip: 0,
        op: 90.0000036657751,
        st: 0,
        bm: 0,
      },
    ],
  };
};

const failure = (primaryColor: ColorValue, overlayColor: ColorValue) => {
  const primary = colorArray(primaryColor);
  const overlay = colorArray(overlayColor);

  return {
    v: '5.1.16',
    fr: 29.9700012207031,
    ip: 0,
    op: 28.0000011404634,
    w: 54,
    h: 54,
    nm: `rejected-${String(primaryColor)}-${String(overlayColor)}`,
    ddd: 0,
    assets: [
      {
        id: 'comp_0',
        layers: [
          {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'check_longアウトライン 2',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 },
              p: { a: 0, k: [54, 54.25, 0], ix: 2 },
              a: { a: 0, k: [54, 54, 0], ix: 1 },
              s: { a: 0, k: [-100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    ind: 0,
                    ty: 'sh',
                    ix: 1,
                    ks: { a: 0, k: { i: [[0, 0]], o: [[0, 0]], v: [[65.375, 62.75]], c: false }, ix: 2 },
                    nm: 'Pfad 1',
                    mn: 'ADBE Vector Shape - Group',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: overlay, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 6, ix: 5 },
                    lc: 1,
                    lj: 1,
                    ml: 4,
                    nm: 'Kontur 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'fl',
                    c: { a: 0, k: [1, 0, 0, 1], ix: 4 },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    nm: 'Fläche 1',
                    mn: 'ADBE Vector Graphic - Fill',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: 'Form 1',
                np: 3,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ind: 1,
                ty: 'sh',
                ix: 2,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [38.688, 69.582],
                      [68.927, 39.353],
                    ],
                    c: false,
                  },
                  ix: 2,
                },
                nm: 'パス 1',
                mn: 'ADBE Vector Shape - Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 24,
                      s: [0],
                      e: [0],
                    },
                    { t: 28.0000011404634 },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 19,
                      s: [0],
                      e: [0],
                    },
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 24,
                      s: [0],
                      e: [100],
                    },
                    { t: 27.0000010997325 },
                  ],
                  ix: 2,
                },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 3,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
              {
                ty: 'st',
                c: { a: 0, k: overlay, ix: 3 },
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 6, ix: 5 },
                lc: 2,
                lj: 2,
                nm: '線 1',
                mn: 'ADBE Vector Graphic - Stroke',
                hd: false,
              },
            ],
            ip: 3.00000012219251,
            op: 93.0000037879676,
            st: 3.00000012219251,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'check_longアウトライン',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [54, 54, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ind: 0,
                ty: 'sh',
                ix: 1,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [7.474, 35.526],
                      [36.621, 71.442],
                      [68.75, 39.177],
                    ],
                    c: false,
                  },
                  ix: 2,
                },
                nm: 'パス 1',
                mn: 'ADBE Vector Shape - Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 21,
                      s: [0],
                      e: [53],
                    },
                    { t: 25.0000010182709 },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [0],
                      e: [100],
                    },
                    { t: 24.00000097754 },
                  ],
                  ix: 2,
                },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
              {
                ty: 'st',
                c: { a: 0, k: overlay, ix: 3 },
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 6, ix: 5 },
                lc: 2,
                lj: 2,
                nm: '線 1',
                mn: 'ADBE Vector Graphic - Stroke',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 3,
            ty: 4,
            nm: 'シェイプレイヤー 4',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [0.833] },
                    o: { x: [0.167], y: [0.167] },
                    n: ['0p833_0p833_0p167_0p167'],
                    t: 0,
                    s: [-68],
                    e: [220],
                  },
                  { t: 16.0000006516934 },
                ],
                ix: 10,
              },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: overlay, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [0],
                      e: [20],
                    },
                    { t: 21.0000008553475 },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 0,
                      s: [20],
                      e: [20],
                    },
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [20],
                      e: [20],
                    },
                    { t: 21.0000008553475 },
                  ],
                  ix: 2,
                },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 4,
            ty: 4,
            nm: 'シェイプレイヤー 3',
            sr: 1,
            ks: {
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: -68, ix: 10 },
              p: { a: 0, k: [54, 54, 0], ix: 2 },
              a: { a: 0, k: [0, 0, 0], ix: 1 },
              s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: { a: 0, k: [100, 100], ix: 2 },
                    p: { a: 0, k: [0, 0], ix: 3 },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: { a: 0, k: primary, ix: 3 },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 5, ix: 5 },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: { a: 0, k: [0, 0], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: { a: 0, k: 0, ix: 1 },
                e: { a: 0, k: 100, ix: 2 },
                o: { a: 0, k: 0, ix: 3 },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
        ],
      },
    ],
    layers: [
      {
        ddd: 0,
        ind: 1,
        ty: 0,
        nm: 'pre2',
        refId: 'comp_0',
        sr: 1,
        ks: {
          o: { a: 0, k: 100, ix: 11 },
          r: { a: 0, k: 0, ix: 10 },
          p: { a: 0, k: [27, 27, 0], ix: 2 },
          a: { a: 0, k: [54, 54, 0], ix: 1 },
          s: { a: 0, k: [50, 50, 100], ix: 6 },
        },
        ao: 0,
        w: 108,
        h: 108,
        ip: 0,
        op: 90.0000036657751,
        st: 0,
        bm: 0,
      },
    ],
  };
};

const error = (primaryColor: ColorValue, overlayColor: ColorValue) => {
  const primary = colorArray(primaryColor);
  const overlay = colorArray(overlayColor);

  return {
    v: '5.1.16',
    fr: 29.9700012207031,
    ip: 0,
    op: 25.0000010182709,
    w: 54,
    h: 54,
    nm: 'done-#ff0000-#0000ff',
    ddd: 0,
    assets: [
      {
        id: 'comp_0',
        layers: [
          {
            ind: 2683,
            nm: 'surface14098',
            ao: 0,
            ip: 0,
            op: 80,
            st: 0,
            ty: 4,
            ks: {
              ty: 'tr',
              o: {
                a: 1,
                k: 100,
              },
              r: {
                k: 0,
              },
              p: {
                k: [54, 54],
              },
              a: {
                k: [54, 54],
              },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: [0, 0], y: [0, 0] },
                    i: { x: [1, 1], y: [1, 1] },
                    t: 0,
                    s: [0, 0],
                  },
                  {
                    o: { x: [0, 0], y: [0, 0] },
                    i: { x: [1, 1], y: [1, 1] },
                    t: 15,
                    s: [0, 0],
                  },
                  {
                    o: { x: [0, 0], y: [0, 0] },
                    i: { x: [1, 1], y: [1, 1] },
                    t: 16,
                    s: [5, 5],
                  },
                  {
                    o: { x: [0, 0], y: [0, 0] },
                    i: { x: [1, 1], y: [1, 1] },
                    t: 20,
                    s: [100, 100],
                  },
                ],
                ix: 6,
              },
              sk: {
                k: 0,
              },
              sa: {
                k: 0,
              },
            },
            shapes: [
              {
                ty: 'gr',
                hd: false,
                nm: 'surface14098',
                it: [
                  {
                    ty: 'gr',
                    hd: false,
                    it: [
                      {
                        ty: 'sh',
                        ks: {
                          k: {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [53.92, 33.89],
                              [77.08, 71.52],
                              [30.37, 71.52],
                            ],
                            c: true,
                          },
                        },
                      },
                      {
                        ty: 'sh',
                        ks: {
                          k: {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [56.37, 45.65],
                              [51.67, 45.65],
                              [51.67, 57.41],
                              [56.37, 57.41],
                            ],
                            c: true,
                          },
                        },
                      },
                      {
                        ty: 'sh',
                        ks: {
                          k: {
                            i: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            o: [
                              [0, 0],
                              [0, 0],
                              [0, 0],
                              [0, 0],
                            ],
                            v: [
                              [56.37, 62.11],
                              [51.67, 62.11],
                              [51.67, 66.81],
                              [56.37, 66.81],
                            ],
                            c: true,
                          },
                        },
                      },
                      {
                        ty: 'fl',
                        o: {
                          k: 100,
                        },
                        c: {
                          k: overlay,
                        },
                      },
                      {
                        ty: 'tr',
                        o: {
                          k: 100,
                        },
                        r: {
                          k: 0,
                        },
                        p: {
                          k: [0, 0],
                        },
                        a: {
                          k: [0, 0],
                        },
                        s: {
                          k: [100, 100],
                        },
                        sk: {
                          k: 0,
                        },
                        sa: {
                          k: 0,
                        },
                        hd: false,
                      },
                    ],
                  },
                  {
                    ty: 'tr',
                    o: {
                      k: 100,
                    },
                    r: {
                      k: 0,
                    },
                    p: {
                      k: [0, 0],
                    },
                    a: {
                      k: [0, 0],
                    },
                    s: {
                      k: [100, 100],
                    },
                    sk: {
                      k: 0,
                    },
                    sa: {
                      k: 0,
                    },
                    hd: false,
                  },
                ],
              },
            ],
          },
          {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'シェイプレイヤー 4',
            sr: 1,
            ks: {
              o: {
                a: 0,
                k: 100,
                ix: 11,
              },
              r: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.833],
                      y: [0.833],
                    },
                    o: {
                      x: [0.167],
                      y: [0.167],
                    },
                    n: ['0p833_0p833_0p167_0p167'],
                    t: 0,
                    s: [-68],
                    e: [220],
                  },
                  {
                    t: 16.0000006516934,
                  },
                ],
                ix: 10,
              },
              p: {
                a: 0,
                k: [54, 54, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100, 100],
                ix: 6,
              },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: {
                      a: 0,
                      k: [100, 100],
                      ix: 2,
                    },
                    p: {
                      a: 0,
                      k: [0, 0],
                      ix: 3,
                    },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: {
                      a: 0,
                      k: overlay,
                      ix: 3,
                    },
                    o: {
                      a: 0,
                      k: 100,
                      ix: 4,
                    },
                    w: {
                      a: 0,
                      k: 5,
                      ix: 5,
                    },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: {
                      a: 0,
                      k: [0, 0],
                      ix: 2,
                    },
                    a: {
                      a: 0,
                      k: [0, 0],
                      ix: 1,
                    },
                    s: {
                      a: 0,
                      k: [100, 100],
                      ix: 3,
                    },
                    r: {
                      a: 0,
                      k: 0,
                      ix: 6,
                    },
                    o: {
                      a: 0,
                      k: 100,
                      ix: 7,
                    },
                    sk: {
                      a: 0,
                      k: 0,
                      ix: 4,
                    },
                    sa: {
                      a: 0,
                      k: 0,
                      ix: 5,
                    },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 1,
                  k: [
                    {
                      i: {
                        x: [0.833],
                        y: [0.833],
                      },
                      o: {
                        x: [0.167],
                        y: [0.167],
                      },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [0],
                      e: [20],
                    },
                    {
                      t: 21.0000008553475,
                    },
                  ],
                  ix: 1,
                },
                e: {
                  a: 1,
                  k: [
                    {
                      i: {
                        x: [0.833],
                        y: [0.833],
                      },
                      o: {
                        x: [0.167],
                        y: [0.167],
                      },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 0,
                      s: [20],
                      e: [20],
                    },
                    {
                      i: {
                        x: [0.833],
                        y: [0.833],
                      },
                      o: {
                        x: [0.167],
                        y: [0.167],
                      },
                      n: ['0p833_0p833_0p167_0p167'],
                      t: 16,
                      s: [20],
                      e: [20],
                    },
                    {
                      t: 21.0000008553475,
                    },
                  ],
                  ix: 2,
                },
                o: {
                  a: 0,
                  k: 0,
                  ix: 3,
                },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
          {
            ddd: 0,
            ind: 3,
            ty: 4,
            nm: 'シェイプレイヤー 3',
            sr: 1,
            ks: {
              o: {
                a: 0,
                k: 100,
                ix: 11,
              },
              r: {
                a: 0,
                k: -68,
                ix: 10,
              },
              p: {
                a: 0,
                k: [54, 54, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100, 100],
                ix: 6,
              },
            },
            ao: 0,
            shapes: [
              {
                ty: 'gr',
                it: [
                  {
                    d: 1,
                    ty: 'el',
                    s: {
                      a: 0,
                      k: [100, 100],
                      ix: 2,
                    },
                    p: {
                      a: 0,
                      k: [0, 0],
                      ix: 3,
                    },
                    nm: '楕円形パス 1',
                    mn: 'ADBE Vector Shape - Ellipse',
                    hd: false,
                  },
                  {
                    ty: 'st',
                    c: {
                      a: 0,
                      k: primary,
                      ix: 3,
                    },
                    o: {
                      a: 0,
                      k: 100,
                      ix: 4,
                    },
                    w: {
                      a: 0,
                      k: 5,
                      ix: 5,
                    },
                    lc: 2,
                    lj: 2,
                    nm: '線 1',
                    mn: 'ADBE Vector Graphic - Stroke',
                    hd: false,
                  },
                  {
                    ty: 'tr',
                    p: {
                      a: 0,
                      k: [0, 0],
                      ix: 2,
                    },
                    a: {
                      a: 0,
                      k: [0, 0],
                      ix: 1,
                    },
                    s: {
                      a: 0,
                      k: [100, 100],
                      ix: 3,
                    },
                    r: {
                      a: 0,
                      k: 0,
                      ix: 6,
                    },
                    o: {
                      a: 0,
                      k: 100,
                      ix: 7,
                    },
                    sk: {
                      a: 0,
                      k: 0,
                      ix: 4,
                    },
                    sa: {
                      a: 0,
                      k: 0,
                      ix: 5,
                    },
                    nm: 'Transformieren',
                  },
                ],
                nm: '楕円形 1',
                np: 2,
                cix: 2,
                ix: 1,
                mn: 'ADBE Vector Group',
                hd: false,
              },
              {
                ty: 'tm',
                s: {
                  a: 0,
                  k: 0,
                  ix: 1,
                },
                e: {
                  a: 0,
                  k: 100,
                  ix: 2,
                },
                o: {
                  a: 0,
                  k: 0,
                  ix: 3,
                },
                m: 1,
                ix: 2,
                nm: 'パスのトリミング 1',
                mn: 'ADBE Vector Filter - Trim',
                hd: false,
              },
            ],
            ip: 0,
            op: 90.0000036657751,
            st: 0,
            bm: 0,
          },
        ],
      },
    ],
    layers: [
      {
        ddd: 0,
        ind: 1,
        ty: 0,
        nm: 'pre4',
        refId: 'comp_0',
        sr: 1,
        ks: {
          o: {
            a: 0,
            k: 100,
            ix: 11,
          },
          r: {
            a: 0,
            k: 0,
            ix: 10,
          },
          p: {
            a: 0,
            k: [27, 27, 0],
            ix: 2,
          },
          a: {
            a: 0,
            k: [54, 54, 0],
            ix: 1,
          },
          s: {
            a: 0,
            k: [49.537, 49.537, 100],
            ix: 6,
          },
        },
        ao: 0,
        w: 108,
        h: 108,
        ip: 0,
        op: 90.0000036657751,
        st: 0,
        bm: 0,
      },
    ],
  };
};

export default { loading, success, failure, error };
